### ISSUE TITLE
Question about loading 

### ISSUE THREAD

**Issue by CableTV1123** [soywiz-archive/jspspemu#11]
I tried playing project diva extended but it looks like it's loading and has been for a while (the files really big)
Is it just loading for a long time because it's big or is it not able to handle it or something
sorry if this was explained bad

**Comment by soywiz** [comment]
The compatibility list is very low, so it is likely that it doesn't work.
Right now I'm only aware of a few games that are running properly.
This is a pet project I use for experimenting and learning for fun, so not big expectations here.

Here you can find the best emulators out there that have awesome compatibility with most of the games:
* https://github.com/hrydgard/ppsspp
* https://github.com/jpcsp/jpcsp
