### ISSUE TITLE
Problem building

### ISSUE THREAD

**Issue by ethanaobrien** [soywiz-archive/jspspemu#13]
I have downloaded the source and I used cd to get the directory but when I try to run `yarn build` I get

`ERROR: [Errno 2] No such file or directory: 'build'`

What do I need to do?

**Comment by soywiz** [comment]
Looking at the CI: https://github.com/jspspemu/jspspemu/blob/514634c45dbfc639327b99f72c2c47c13100f3c1/.github/workflows/test.yml#L17-L25

It executes:
```
npm install
yarn build
```

Can you try to execute `npm install` first just in case?

**Comment by ethanaobrien** [comment]
@soywiz 
It worked... ish. When I ran npm install It gave me a ton of errors but yarn build would work after that.
![Screenshot 2021-05-04 1 06 45 PM](https://user-images.githubusercontent.com/77750390/117049351-9efa0c00-acd9-11eb-9d9d-0353d4487234.png)

And from the looks of this it is just because I am using termux. So yes, npm install first made it work (Should this be updated in the readme?)
![Screenshot 2021-05-04 1 09 27 PM](https://user-images.githubusercontent.com/77750390/117049617-fa2bfe80-acd9-11eb-8f3c-b1e9351b705d.png)

 Should I close this?

**Comment by soywiz** [comment]
It looks that you are trying to run it on an android device or emulator right? The dependency that is not supported for the android x86 LE target is esbuild: https://github.com/evanw/esbuild Not sure if they will support it, but if you want support for it, you should open an issue there

**Comment by ethanaobrien** [comment]
@soywiz Thanks! I was actually running it on chrome os so I can just enable and use linux (beta). Ill close this now

**Comment by ethanaobrien** [comment]
@soywiz 

I just tested in linux beta and I did not have to run any yarn commands. I ran
1. npm install
2. npm run build
3. npm run serve

Should this be updated in the readme?

**Comment by soywiz** [comment]
Yeah, in the end `yarn something` is like `npm run something`, I just use it for convenience, but feel free to make a PR with `npm run` if you believe it reads better :)
